#!/bin/sh

set -e

printusage() {
         echo "\n       ERROR: 1 or 3 arguments required.\n\n"

         echo "Usage: $0 initdb [LANG EN]"
         echo "       $0 newlocale [LANG EN]"
         echo ""
         echo "       $0 initdb en_US UTF-8"
         echo "       $0 newlocale en_GB UTF-8"
         echo "\n"
         echo "       If LANG and EN are not provided en_US UTF-8 is used as defaults.\n"
}

#
# Usage checks
#

if [ "$1" = "newlocale" -a \( -z "$2" -o -z "$3" \) ]; then

 printusage
 exit

fi

#
# Set locale defaults
#

if [ ! -z "$2" ]; then
  LOCLANG="$2"
else
  LOCLANG="en_US"
fi

if [ ! -z "$3" ]; then
  LOCEN="$3"
else
  LOCEN="UTF-8"
fi

#
# Environment variables
# Locale

LOC="$LOCLANG.$LOCEN"

export LANG=$LOC
export I18NPATH=$SNAP/usr/share/i18n
export LOCPATH=$SNAP_COMMON/postgresql/locales

# PostgreSQL

PG_ROOT_DIR="$SNAP_COMMON/postgresql"
DATA_DIR="$PG_ROOT_DIR/data"
LOG_DIR="$PG_ROOT_DIR/logs"
PSQLHIST_DIR="$PG_ROOT_DIR/history"
POSTGRES_CONFIG_FILENAME="postgresql.conf"

#
# Functions
#

snap_daemon_run_command() {
     "$SNAP/usr/bin/setpriv" --clear-groups --reuid snap_daemon --regid snap_daemon -- "$@"
}

localegen() {
if [ ! -e $LOCPATH/$LOC ]; then
echo "Generating a new locale in $LOCPATH/$LOC..."
  mkdir -p "$LOCPATH/$LOC"
  chown -R snap_daemon:snap_daemon "$LOCPATH"

  snap_daemon_run_command $SNAP/usr/bin/localedef --prefix=$LOCPATH -f $LOCEN -i $LOCLANG $LOCPATH/$LOC
fi
}


pginit() {
echo "Setting up PostgreSQL environment..."

echo "Root directory: $PG_ROOT_DIR"
if [ ! -e "$PG_ROOT_DIR" ]; then
  mkdir -p "$PG_ROOT_DIR"
  chown snap_daemon:snap_daemon "$PG_ROOT_DIR"
fi

echo "Data directory: $DATA_DIR"
if [ ! -e "$DATA_DIR" ]; then
  mkdir -p "$DATA_DIR"
  chown snap_daemon:snap_daemon "$DATA_DIR"
fi

echo "Logs directory: $LOG_DIR"
if [ ! -e "$LOG_DIR" ]; then
  mkdir -p "$LOG_DIR"
  chown snap_daemon:snap_daemon "$LOG_DIR"
fi

echo "psql history directory: $PSQLHIST_DIR"
if [ ! -e "$PSQLHIST_DIR" ]; then
  mkdir -p "$PSQLHIST_DIR"
  chown snap_daemon:snap_daemon "$PSQLHIST_DIR"
fi

echo ".psqlrc file: $SNAP_COMMON/.psqlrc"
if [ ! -e "$SNAP_COMMON/.psqlrc" ]; then
  echo "\set HISTFILE $PSQLHIST_DIR/psql_history- :DBNAME" > $SNAP_COMMON/.psqlrc
  chown snap_daemon:snap_daemon $SNAP_COMMON/.psqlrc
fi

echo "Checking if initdb has already been run before. If not, a new cluster will be created."
[ -e "$DATA_DIR/base" ] || snap_daemon_run_command $SNAP/usr/lib/postgresql/14/bin/initdb -D $DATA_DIR

echo "Create postgres config file"
if [ ! -e "$DATA_DIR/$POSTGRES_CONFIG_FILENAME" ]; then
 snap_daemon_run_command cp "$SNAP/$POSTGRES_CONFIG_FILENAME" "$DATA_DIR/"

 # do replacement of the $SNAP, $SNAP_DATA, $SNAP_COMMON environment variables in the config files
 snap_daemon_run_command sed -i -e "s@\$SNAP_COMMON@$SNAP_COMMON@g" \
        -e "s@\$SNAP_DATA@$CURRENT@g" \
        -e "s@\$SNAP@$SNAP_CURRENT@g" \
        "$DATA_DIR/$POSTGRES_CONFIG_FILENAME"
fi

echo "Create sockets dir"
if [ ! -e "$SNAP_COMMON/sockets" ]; then
  mkdir -p $SNAP_COMMON/sockets
  chown snap_daemon:snap_daemon $SNAP_COMMON/sockets
fi
}


#
# Main script
#

case $1 in
      initdb)
	 localegen
         pginit
         ;;
      newlocale)
         localegen
         ;;
      *)
         printusage
esac

