#!/bin/sh

set -e

#
# Locale configuration
#
export I18NPATH=$SNAP/usr/share/i18n
export LOCPATH=$SNAP_COMMON/postgresql/locales

LOCLANG=en_US
LOCEN=UTF-8
LOC="$LOCLANG.$LOCEN"

export LANG=$LOC

snap_daemon_run_command() {
     "$SNAP/usr/bin/setpriv" --clear-groups --reuid snap_daemon --regid snap_daemon -- "$@"
}

snap_daemon_run_command $SNAP/usr/lib/postgresql/14/bin/pg_ctl "$@"


