#!/bin/sh

set -e

export PSQLRC="$SNAP_COMMON/.psqlrc"

snap_daemon_run_command() {
     "$SNAP/usr/bin/setpriv" --clear-groups --reuid snap_daemon --regid snap_daemon -- "$@"
}

snap_daemon_run_command $SNAP/usr/lib/postgresql/14/bin/psql "$@"


