#!/bin/sh

# shellcheck source=scripts/postgres.shlib
. "${SNAP}/usr/bin/postgres.shlib"

localegen() {
  [ ! -e "${LOCPATH}/${LOC}" ] ||
    return 0

  echo "Generating a new locale in ${LOCPATH}/${LOC}..."
  mkdir -p "${LOCPATH}/${LOC}"
  chown -R snap_daemon:snap_daemon "${LOCPATH}"

  run "${SNAP}/usr/bin/localedef" \
    --prefix="${LOCPATH}" \
    -f "${LOC_ENCODING}" \
    -i "${LOC_LANG}" \
    "${LOCPATH}/${LOC}"
}

pginit() {
  echo "Setting up PostgreSQL environment..."
  for path in "${DATA_DIR}" "${LOG_DIR}" "${PSQLHIST_DIR}" "${SOCK_DIR}"; do
    [ ! -e "${path}" ] ||
      continue

    mkdir -p "${path}"
    chown snap_daemon:snap_daemon "${path}"
  done

  echo ".psqlrc file: ${PSQLRC}"
  [ -e "${PSQLRC}" ] || {
    printf >"${PSQLRC}" \
      '\set HISTFILE %s/psql_history- :DBNAME' \
      "${PSQLHIST_DIR}"
    chown snap_daemon:snap_daemon "${PSQLRC}"
  }

  echo "Checking if initdb has already been run before. If not, a new cluster will be created."
  [ -e "${DATA_DIR}/postgresql.conf" ] ||
    run "${SNAP}/usr/lib/postgresql/16/bin/initdb" \
      --username postgres \
      --auth-host scram-sha-256 \
      --set "unix_socket_directories=${SOCK_DIR}"
}

main() {
  set -eu

  localegen
  pginit
}

main "$@"
