name: postgresql
base: core24
adopt-info: postgresql
summary: PostgreSQL is a powerful, open source object-relational database system.
description: |
  PostgreSQL is a powerful, open source object-relational database system.
  It has more than 15 years of active development and a proven architecture
  that has earned it a strong reputation for reliability, data integrity,
  and correctness.
confinement: strict
grade: stable

system-usernames:
  snap_daemon: shared

assumes: [snapd2.45]

apps:
  daemon:
    install-mode: disable
    daemon: forking
    command: usr/bin/wrapper-pg_ctl start -l $SNAP_COMMON/postgresql/logs/postgres.log -D $SNAP_COMMON/postgresql/data 
    command-chain: [bin/snapcraft-preload]
    plugs:
      - home
      - network
      - network-bind
      - shared-memory
    environment:
      SNAPCRAFT_PRELOAD_REDIRECT_ONLY_SHM: "1"
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR 
  psql:
    command: usr/bin/wrapper-psql
    plugs: 
      - home
      - network

parts:
  postgresql:
    plugin: nil
    override-build: |
      craftctl set version="$(apt-show-versions -a postgresql-16 | head -n -1 | tail -1 | cut -f2 -d' ')"
    build-packages:
      - apt-show-versions
    stage-packages:
      - postgresql-16
      - postgresql-contrib
      - libecpg-dev
      - libc-bin
      - locales
      - util-linux

  wrappers:
    plugin: dump
    source: wrappers
    organize:
      '*': usr/bin/

  config:
    plugin: dump
    source: config

  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - to arm64:
        - g++-arm-linux-gnueabihf
        - gcc-arm-linux-gnueabihf
      - else:
        - gcc-multilib
        - g++-multilib
    stage-packages:
      - to amd64:
        - lib32stdc++6 
    override-build: |
      cd $CRAFT_PART_SRC 
      cmake -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/ .
      make install

plugs:
  shared-memory:
    private: true
