name: postgresql14
version: "14.0"
base: core22
summary: PostgreSQL is a powerful, open source object-relational database system.
description: |
  PostgreSQL is a powerful, open source object-relational database system.
  It has more than 15 years of active development and a proven architecture
  that has earned it a strong reputation for reliability, data integrity,
  and correctness.
confinement: strict
grade: stable

system-usernames:
  snap_daemon: shared

assumes: [snapd2.45]

apps:
  postgres-service:
       install-mode: disable
       daemon: forking
       command: usr/bin/wrapper-pg_ctl start -l $SNAP_COMMON/postgresql/logs/postgres.log -D $SNAP_COMMON/postgresql/data 
       command-chain: [bin/snapcraft-preload]
       plugs:
         - network
         - network-bind
       environment:
         SNAPCRAFT_PRELOAD_REDIRECT_ONLY_SHM: 1
  psql:
       command: usr/bin/wrapper-psql
       plugs: [network]
  
parts:
  postgresql:
    plugin: nil
    stage-packages:
        - postgresql
        - postgresql-contrib
        - libecpg-dev
        - libc-bin
        - locales
        - util-linux
  wrapper:
    plugin: make
    source: .

  config:
    plugin: dump
    source: config

  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages:
      - to arm64:
          - g++-arm-linux-gnueabihf
          - gcc-arm-linux-gnueabihf
      - else:
          - gcc-multilib
          - g++-multilib
    stage-packages:
      - to amd64:
          - lib32stdc++6 
    override-build: |
      cd $CRAFT_PART_SRC 
      cmake -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/ .
      make install

environment:
        LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET 

plugs:
  home:
